//! Hub route - central passives, movement, and route connector chains.

use super::{stat_node, PrerequisiteMode, Route, TalentId, TalentNode, TalentStat, TalentStatus};

pub const CONNECTOR_WARRIOR_TAIL: TalentId = TalentId(111);
pub const CONNECTOR_MAGE_TAIL: TalentId = TalentId(211);
pub const CONNECTOR_HEALER_TAIL: TalentId = TalentId(311);
pub const CONNECTOR_SUMMONER_TAIL: TalentId = TalentId(411);

pub fn nodes() -> Vec<TalentNode> {
    use PrerequisiteMode::All;
    use TalentStat::*;
    use TalentStatus::*;

    vec![
        stat_node(
            1,
            "Vigor",
            "+3% max HP per rank.",
            Route::Hub,
            MaxHp,
            0.03,
            3,
            &[],
            All,
            Ready,
            (0.0, -120.0),
        ),
        stat_node(
            2,
            "Might",
            "+3% damage per rank.",
            Route::Hub,
            Damage,
            0.03,
            3,
            &[],
            All,
            Ready,
            (190.0, -115.0),
        ),
        stat_node(
            3,
            "Keen Edge",
            "+1% crit chance per rank.",
            Route::Hub,
            CritChance,
            0.01,
            3,
            &[],
            All,
            Ready,
            (0.0, -190.0),
        ),
        stat_node(
            4,
            "Focus",
            "+2% cooldown reduction per rank.",
            Route::Hub,
            CooldownReduction,
            0.02,
            3,
            &[],
            All,
            Ready,
            (45.0, 125.0),
        ),
        stat_node(
            5,
            "Toughness",
            "+3% armor per rank.",
            Route::Hub,
            Defense,
            0.03,
            3,
            &[],
            All,
            Ready,
            (-45.0, 125.0),
        ),
        stat_node(
            6,
            "Swift Step",
            "+2% move speed per rank.",
            Route::Hub,
            MoveSpeed,
            0.02,
            3,
            &[],
            All,
            Ready,
            (-125.0, 45.0),
        ),
        stat_node(
            7,
            "Reflexes",
            "+2% attack speed per rank.",
            Route::Hub,
            AttackSpeed,
            0.02,
            3,
            &[],
            All,
            Ready,
            (125.0, 45.0),
        ),
        stat_node(
            8,
            "Precision",
            "+5% crit damage per rank.",
            Route::Hub,
            CritDamage,
            0.05,
            3,
            &[],
            All,
            Ready,
            (-125.0, -45.0),
        ),
        stat_node(
            9,
            "Recovery",
            "+2% health recovery or potion value per rank.",
            Route::Hub,
            MaxHp,
            0.02,
            3,
            &[],
            All,
            NeedsSystem,
            (185.0, 75.0),
        ),
        stat_node(
            10,
            "Discipline",
            "+2% control resistance per rank.",
            Route::Hub,
            Defense,
            0.02,
            3,
            &[],
            All,
            NeedsSystem,
            (-260.0, 50.0),
        ),
        stat_node(
            100,
            "Tumbler",
            "+3% move speed per rank.",
            Route::Hub,
            MoveSpeed,
            0.03,
            3,
            &[6],
            All,
            Ready,
            (-230.0, 130.0),
        ),
        stat_node(
            110,
            "Strength",
            "+2% damage.",
            Route::Hub,
            Damage,
            0.02,
            1,
            &[2],
            All,
            Ready,
            (230.0, -35.0),
        ),
        stat_node(
            111,
            "Endurance",
            "+2% max HP.",
            Route::Hub,
            MaxHp,
            0.02,
            1,
            &[110],
            All,
            Ready,
            (330.0, -15.0),
        ),
        stat_node(
            210,
            "Insight",
            "+1% crit chance.",
            Route::Hub,
            CritChance,
            0.01,
            1,
            &[3],
            All,
            Ready,
            (70.0, -260.0),
        ),
        stat_node(
            211,
            "Channeling",
            "+2% cooldown reduction.",
            Route::Hub,
            CooldownReduction,
            0.02,
            1,
            &[210],
            All,
            Ready,
            (30.0, -360.0),
        ),
        stat_node(
            310,
            "Compassion",
            "+2% max HP.",
            Route::Hub,
            MaxHp,
            0.02,
            1,
            &[1],
            All,
            Ready,
            (0.0, 250.0),
        ),
        stat_node(
            311,
            "Devotion",
            "+2% cooldown reduction.",
            Route::Hub,
            CooldownReduction,
            0.02,
            1,
            &[310],
            All,
            Ready,
            (0.0, 350.0),
        ),
        stat_node(
            410,
            "Ominous Bond",
            "+2% damage.",
            Route::Hub,
            Damage,
            0.02,
            1,
            &[8],
            All,
            Ready,
            (-250.0, -35.0),
        ),
        stat_node(
            411,
            "Rift Sympathy",
            "+1% crit chance.",
            Route::Hub,
            CritChance,
            0.01,
            1,
            &[410],
            All,
            Ready,
            (-360.0, -15.0),
        ),
    ]
}
